branches:
  only:
    - node-pre-gyp
    - /^[0-9]/

language: cpp

services:
  - docker
    
dist: trusty

env:
  matrix:
  - NODE_VERSION="0.12"
  - NODE_VERSION="4"
  - NODE_VERSION="5"
  - NODE_VERSION="6"

before_install:
  - sudo apt-get install build-essential libudev-dev -y
  - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
  - echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:' | sudo tee -a /proc/sys/fs/binfmt_misc/register
  - export NVM_DIR=~/.nvm
  - . $HOME/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node --version
  - npm --version

install:
- export PATH=./node_modules/.bin/:$PATH
- npm install -g node-pre-gyp-github

script:
- npm install --build-from-source --node-gyp=$(which pangyp)
- "./node_modules/.bin/node-pre-gyp package"
- cp /usr/bin/qemu-arm-static ./
- docker build -t sandeepmistry/node-bluetooth-hci-socket:master ./
- docker run --rm -i -t multiarch/ubuntu-core:armhf-trusty /usr/bin/uname -a
- docker run --rm -i -t multiarch/ubuntu-core:arm64-trusty /usr/bin/uname -a
- echo $TRAVIS_TAG
- >
    ([[ "$TRAVIS_TAG" =~ ^[0-9] ]] &&
    node-pre-gyp-github publish) || true
