branches:
  only:
    - docker-arm-build
    - /^[0-9]/

language: cpp

services:
  - docker

dist: trusty

env:
  matrix:
  - NODE_VERSION="6"

before_install:
  - sudo apt-get install build-essential libudev-dev -y
  - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
  - echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:' | sudo tee -a /proc/sys/fs/binfmt_misc/register

script:
- docker run -e "NODE_VERSION=$NODE_VERSION" --rm -i -v $(pwd):/root/workspace -t multiarch/ubuntu-core:armhf-trusty /bin/bash -c /root/workspace/build.sh
- docker run -e "NODE_VERSION=$NODE_VERSION" --rm -i -v $(pwd):/root/workspace -t multiarch/ubuntu-core:arm64-trusty /bin/bash -c /root/workspace/build.sh
- echo $TRAVIS_TAG
- >
    ([[ "$TRAVIS_TAG" =~ ^[0-9] ]] &&
    node-pre-gyp-github publish) || true
